"""empty message

Revision ID: 2b42fd7f826f
Revises: ed085e39ec87
Create Date: 2023-06-02 18:30:51.305106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b42fd7f826f'
down_revision = 'ed085e39ec87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caught_pokemon',
    sa.Column('user_caught_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_caught', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_caught'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_caught_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caught_pokemon')
    # ### end Alembic commands ###
