"""empty message

Revision ID: 52ad1c22d8cd
Revises: 
Create Date: 2023-06-03 12:10:21.452615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ad1c22d8cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon',
    sa.Column('pokemon_name', sa.String(), nullable=False),
    sa.Column('ability', sa.String(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pokemon_name'),
    sa.UniqueConstraint('pokemon_name')
    )
    op.create_table('caught_pokemon',
    sa.Column('user_caught_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_caught', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_caught'], ['pokemon.pokemon_name'], ),
    sa.ForeignKeyConstraint(['user_caught_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caught_pokemon')
    op.drop_table('pokemon')
    op.drop_table('user')
    # ### end Alembic commands ###
