"""empty message

Revision ID: 7c0fc7d5789d
Revises: 2b42fd7f826f
Create Date: 2023-06-02 18:46:28.138750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0fc7d5789d'
down_revision = '2b42fd7f826f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caught_pokemon',
    sa.Column('user_caught_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_caught', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_caught'], ['pokemon.pokemon_name'], ),
    sa.ForeignKeyConstraint(['user_caught_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caught_pokemon')
    # ### end Alembic commands ###
