"""empty message

Revision ID: c00c25a6a922
Revises: e348c7421d3e
Create Date: 2023-06-08 20:09:39.110398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00c25a6a922'
down_revision = 'e348c7421d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caught_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pokemon_name', sa.String(), nullable=True))
        batch_op.drop_constraint('caught_pokemon_pokemon_caught_fkey', type_='foreignkey')
        batch_op.drop_constraint('caught_pokemon_user_caught_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'pokemon', ['pokemon_name'], ['pokemon_name'])
        batch_op.drop_column('pokemon_caught')
        batch_op.drop_column('user_caught_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caught_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_caught_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pokemon_caught', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('caught_pokemon_user_caught_id_fkey', 'user', ['user_caught_id'], ['id'])
        batch_op.create_foreign_key('caught_pokemon_pokemon_caught_fkey', 'pokemon', ['pokemon_caught'], ['pokemon_name'])
        batch_op.drop_column('pokemon_name')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
